// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['docklister']['App']['Greet'](arg1);
}

export function ListImages() {
  return window['go']['docklister']['App']['ListImages']();
}
